### ISSUE TITLE
US-02 As a user, I would like to create, edit, view a post which contains a picture with title and body

### ISSUE THREAD

**Issue by marksman1298** [abdulmansour/soen341#3]
UI:
- [x] create a button to load a picture
- [x] create a button to delete a picture
- [x] create a button to edit picture

DB:
- [x] store loaded picture into filesystem/db
- [x] create a 'posts' table with fields (picture_path, description, timestamp)
- [x] add newly created post into 'posts' table

**Comment by abdulmansour** [comment]
For image uploading: 
need to run:
sudo chmod 777 Applications/XAMPP/xamppfiles/htdocs/soen341/storage/

to allow writing to storage file

**Comment by TommySoucy** [comment]
![US2Test](https://user-images.githubusercontent.com/45676781/75991247-32606300-5ec4-11ea-8061-841aed0f3bee.PNG)
